kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: f+ChBag4tAT8k47SHJOvhHI+YCdO4d7nrokRq/fRhTI=
      - identity: {}